# Generated by Django 5.1.1 on 2024-10-15 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='https://sudoteam.s3.eu-north-1.amazonaws.com/default_avatar.png', upload_to='profile_images'),
        ),
    ]
