# Generated by Django 5.1.1 on 2024-10-12 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0002_note_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='item',
        ),
    ]
