# Generated by Django 5.1.1 on 2024-10-08 03:35

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', cloudinary.models.CloudinaryField(max_length=255, verbose_name='file')),
                ('category', models.CharField(choices=[('image', 'Image'), ('document', 'Document'), ('video', 'Video')], max_length=20)),
            ],
        ),
    ]
