# Generated by Django 5.1.1 on 2024-10-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files_app', '0002_file_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='category',
            field=models.CharField(choices=[('image', 'Image'), ('document', 'Document'), ('video', 'Video'), ('other', 'Other')], max_length=20),
        ),
    ]
