# Generated by Django 5.1.1 on 2024-10-08 13:05

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files_app', '0003_alter_file_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='preview',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='preview'),
        ),
    ]
