# Generated by Django 5.1.1 on 2024-10-09 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files_app', '0004_file_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='original_extension',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
