# Generated by Django 5.1.1 on 2024-10-09 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files_app', '0005_file_original_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
