# Generated by Django 5.1.1 on 2024-10-10 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files_app', '0006_file_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='resource_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
